global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sentinel-api"
    static_configs:
      - targets: ["host.docker.internal:9464"]
        labels:
          application: "sentinel-api"
